scp luke@cadence:/data/mir3/iodfitsdb/ij205.304.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij205.304.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.512.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.512.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.512.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.1005.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij304.185.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij274.108.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij274.108.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.514.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.514.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.514.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.514.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.82.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.82.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.796.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2480.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2480.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2211.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2211.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.85.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.85.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.85.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.85.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.719.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.719.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.401.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.411.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1279.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1279.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.513.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.513.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.1197.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.1197.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.524.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.524.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij291.101.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij334.296.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.901.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.901.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.901.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.530.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.402.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1190.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.75.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1190.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.75.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1190.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.75.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1190.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.75.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1190.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.75.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij92.153.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij92.153.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.689.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.689.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.689.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.689.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2370.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.902.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1274.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1274.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1274.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij140.66.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij140.66.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij140.66.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij140.66.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij129.323.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij129.323.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij334.293.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.904.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.904.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij134.422.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij134.422.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij295.495.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij295.495.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij295.495.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.642.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.926.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.926.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij127.889.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij302.85.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.934.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij213.113.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij213.113.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij305.81.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.690.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.690.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.690.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.2102.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij336.106.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.685.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.281.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.485.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.485.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.492.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij147.133.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.86.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij147.133.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.86.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij147.133.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.86.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij147.133.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.86.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij147.133.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij123.86.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.285.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.295.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.320.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.491.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij191.160.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij191.160.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij191.160.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij300.279.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.522.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij203.272.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij203.272.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.671.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.293.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.709.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.709.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.976.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.976.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.80.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2369.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2369.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2369.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.486.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.493.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.821.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.821.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.821.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij204.966.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij204.966.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.702.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.702.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij339.286.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.505.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1100.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1100.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij304.182.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij304.182.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.286.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij181.89.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij181.89.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij119.1137.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.81.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.81.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.107.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.283.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.283.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.283.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.283.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij128.490.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij76.2281.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.2288.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij150.313.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.337.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.146.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1187.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1187.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1187.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1187.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.492.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.495.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij150.753.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.114.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij191.286.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij191.286.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2209.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2209.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1890.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1890.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.1002.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij274.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij274.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.422.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.422.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.343.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.343.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.343.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij305.381.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij173.980.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij134.209.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.295.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.304.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij297.92.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij125.102.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.284.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.284.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.284.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.284.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.284.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.289.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.289.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.680.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.507.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.1088.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.507.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.1088.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.76.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.76.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.76.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.802.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij125.108.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij128.283.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij194.287.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij194.303.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.820.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.820.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.820.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij191.162.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij490.285.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.988.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij150.534.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.298.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.873.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij521.168.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.873.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij521.168.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.98.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.526.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.526.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.490.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.490.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.277.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2207.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2207.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.103.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.103.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.103.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.676.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.676.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.676.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij294.123.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.340.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.685.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.796.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.796.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.99.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.99.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.574.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.711.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.1319.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.1319.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.1319.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.693.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.288.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.288.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij339.96.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1075.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1075.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.892.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.508.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.1237.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.1237.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.144.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.628.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.628.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.532.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij170.88.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij294.96.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.485.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.676.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.795.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.879.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.514.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij150.754.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.518.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij171.325.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.288.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.288.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.288.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij148.163.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.935.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.1113.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.298.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.286.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.286.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.278.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.1119.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.930.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij204.854.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij204.854.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij204.854.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.513.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij171.326.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.2103.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.2103.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.2103.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.668.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.533.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.533.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.1378.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij150.521.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij482.184.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.421.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.2101.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij98.96.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij183.386.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.1112.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.324.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.1275.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.51.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.51.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.51.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij133.595.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.291.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.1198.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.102.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij204.967.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij204.967.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.510.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij336.107.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.510.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij336.107.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.706.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij305.383.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.277.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij150.752.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.1288.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.1287.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.485.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.512.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.512.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.512.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.389.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij516.100.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.669.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.669.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.800.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.800.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.704.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.704.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.492.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij330.298.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij134.202.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij134.202.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.681.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.94.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij155.474.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.975.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.975.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij304.186.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij134.201.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij331.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.686.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.106.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.694.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.97.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij334.91.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.52.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.682.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij305.1472.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.307.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij182.400.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.667.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.667.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.505.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.505.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij302.83.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij137.68.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.683.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.679.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.506.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.510.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.1007.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.1007.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.276.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij413.72.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij413.71.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.292.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.306.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.306.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij490.93.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.517.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.985.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.375.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij150.518.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.306.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij213.116.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij213.116.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.501.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.338.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.501.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.338.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.501.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.338.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij295.298.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij149.192.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij149.192.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.1812.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.684.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.684.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.503.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.484.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.484.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.484.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.2522.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.792.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij119.1128.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1191.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.688.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.286.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.1289.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.85.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.288.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.85.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.288.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.672.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.932.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij180.497.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.83.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.83.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij299.90.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij191.464.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.308.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.308.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.285.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.798.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.798.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.87.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.98.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.378.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.304.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.1320.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.1190.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij182.399.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.1368.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.68.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij291.106.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij204.483.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.296.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij296.496.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.272.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.272.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.272.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.272.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.272.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij302.469.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.290.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.290.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.524.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.274.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij124.335.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.701.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.510.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.510.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.905.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.694.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij303.50.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij148.165.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij304.181.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij172.60.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij170.720.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij155.75.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.693.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij155.75.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij152.693.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.496.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.988.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.294.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.294.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.294.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij302.264.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij177.101.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij304.183.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.310.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij194.305.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij194.305.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.740.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij170.515.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij302.265.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.323.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.641.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.723.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.289.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij128.83.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij97.1482.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij389.1891.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij127.890.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij97.1493.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.741.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1291.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij233.122.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij116.207.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij131.700.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1181.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1181.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1181.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.471.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij233.1509.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1291.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.90.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.467.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.1350.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij124.333.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij124.333.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.92.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.856.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.856.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.896.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.896.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.928.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.86.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.96.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij294.97.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij172.1090.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij172.1090.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.914.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.914.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.1006.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.901.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.871.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.871.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.523.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.739.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.730.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.748.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij128.77.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij96.89.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.900.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.1126.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.736.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.290.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.347.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.637.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.314.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij117.637.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.314.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij172.739.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij128.81.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij97.302.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.859.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij211.300.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij211.300.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij211.300.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij211.300.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij194.526.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.774.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij97.1478.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.774.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij97.1478.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.774.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij97.1478.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.774.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij97.1478.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.774.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij97.1478.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij137.204.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij137.204.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.1497.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.1497.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.1497.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij124.334.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.105.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.105.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.525.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.525.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.791.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.791.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1269.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1269.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij190.400.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.695.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij157.695.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.275.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij134.420.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij127.706.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij127.706.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij127.706.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij127.706.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij127.706.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij169.120.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.583.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.824.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij134.208.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.708.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.708.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij202.708.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.486.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.486.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.486.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.486.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij153.486.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.280.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.280.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.280.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.290.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.290.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.290.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.290.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.904.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.904.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.904.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.904.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij205.100.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij205.100.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.1496.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.1496.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij133.594.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.344.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.344.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.344.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij154.344.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.906.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.906.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.906.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.906.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.767.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij121.322.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.297.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.1363.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.732.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.857.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1491.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1491.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.283.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.283.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.283.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.283.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.1359.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.1359.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.870.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.482.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij205.306.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij205.306.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij300.277.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.1358.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1304.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1304.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.1134.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1320.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1320.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.1320.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.747.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.747.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij122.780.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij76.1511.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.293.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij118.1348.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.498.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.498.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij130.498.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2506.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2506.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.2506.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij129.325.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij129.325.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij129.325.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij129.325.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.1127.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.1127.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij120.1127.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij127.722.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij127.722.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.83.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij156.83.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.293.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.293.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.293.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij330.297.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij178.113.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij172.67.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.495.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij178.298.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij173.1197.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij181.103.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij484.88.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij170.506.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij170.510.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.84.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij173.1196.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij194.1089.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1079.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.529.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.275.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij299.91.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.112.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.388.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.304.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij178.116.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij176.118.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.987.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.710.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij485.80.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij180.477.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij173.95.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij178.114.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij194.1296.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.310.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.504.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.473.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.702.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij294.122.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij176.121.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.506.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.693.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.692.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.284.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.697.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij490.478.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij518.322.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij155.273.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.320.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij172.69.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.509.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij486.71.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.287.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.377.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.678.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij290.679.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.487.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.912.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.383.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij158.1394.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.303.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.87.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij385.883.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij173.1193.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij490.92.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.895.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.895.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij179.895.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij172.1101.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij172.1101.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij194.96.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij149.185.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij173.109.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.282.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij294.78.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij170.693.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.514.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.808.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij294.121.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij194.695.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij293.287.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij299.99.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij173.1400.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.703.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij173.113.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij486.74.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij483.383.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.285.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij161.285.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij170.295.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij180.289.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij159.103.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij192.294.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij292.794.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij170.509.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij405.85.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij385.1299.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.307.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij189.1293.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij193.1494.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij384.99.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij438.82.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij516.105.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij295.296.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij201.1199.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.306.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.21.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij333.21.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij332.87.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
scp luke@cadence:/data/mir3/iodfitsdb/ij330.282.fits /Users/luke/local/gyrojo_HIRES_lithium/. 
